### ISSUE TITLE
Error with the new Update 1.8.2

### ISSUE THREAD

**Issue by DevDokus** [overextended/oxmysql#71]
Hey guys, first of all great work on the wrapper!
The database handling goes much faster and smoother then using mysql-async. 

But I removed the old OX files and inserted the new once that where provided in my
server console. Ox now does not want to start due to the following error. 
![Screenshot_2](https://user-images.githubusercontent.com/49053928/144334672-bf37c146-4d66-45b4-910e-be422392c90f.png)

Then you guys know about it :)
Keep up the good work!

EDIT: I also see this error popping up later. Maybe it helps to know
![image](https://user-images.githubusercontent.com/49053928/144334785-c62bacc1-80cd-4782-b2c8-a2567a9036b2.png)

**Comment by rhyfii** [comment]
I'm having the exact same issue as DevDokus. 
![image](https://user-images.githubusercontent.com/86960739/144341609-4c43641e-0caa-4c65-91b6-60ae64e3bb11.png)

Currently using this connection string format as per the documentation;
set mysql_connection_string "user=root;database=es_extended;password=12345;charset=utf8mb4"

**Comment by thelindat** [comment]
Resolved with v1.8.3

**Comment by meltynetv2** [comment]
<img width="661" alt="7a9e7222cfb9f2fce92a36aaa4e6dc0e" src="https://user-images.githubusercontent.com/80143520/144513808-248fdc15-bea4-4eed-b6d8-e32a2f2e6ba0.png">

Hello, I am still getting this error with the 1.8.2 and 1.8.3 release, first occurring on the 1.8.2. Maybe you can look into this as its been starting the resource.


> Resolved with v1.8.3

**Comment by thelindat** [comment]
> <img alt="7a9e7222cfb9f2fce92a36aaa4e6dc0e" width="661" src="https://user-images.githubusercontent.com/80143520/144513808-248fdc15-bea4-4eed-b6d8-e32a2f2e6ba0.png">
> 
> Hello, I am still getting this error with the 1.8.2 and 1.8.3 release, first occurring on the 1.8.2. Maybe you can look into this? I am using the complete clean and un edited version of oxmysql 1.8.3. It works with version 1.8.1 and lower.
> 
That's a different bug, and should have also been resolved. Unless for some reason you actually can't check for undefined natives in JS, which seems idiotic.

Just stop using the nearly 4 month old recommended artifact.

**Comment by meltynetv2** [comment]
> > <img alt="7a9e7222cfb9f2fce92a36aaa4e6dc0e" width="661" src="https://user-images.githubusercontent.com/80143520/144513808-248fdc15-bea4-4eed-b6d8-e32a2f2e6ba0.png">
> > Hello, I am still getting this error with the 1.8.2 and 1.8.3 release, first occurring on the 1.8.2. Maybe you can look into this? I am using the complete clean and un edited version of oxmysql 1.8.3. It works with version 1.8.1 and lower.
> 
> That's a different bug, and should have also been resolved. Unless for some reason you actually can't check for undefined natives in JS, which seems idiotic.
> 
> Just stop using the nearly 4 month old recommended artifact.

<img width="157" alt="3de78e1a8655e2ed9c4a89912cd299dd" src="https://user-images.githubusercontent.com/80143520/144543240-d7a43144-c959-40fa-8ff0-99559445218a.png">

I know this is a different bug, but they both happen on startup which never happened before 1.8.2-3. This is the artifact I'm on which is not the recommended, it is the most recent optional artifact. I am not sure why I am getting this error as 1.8.1 works fine. I tried 1.8.2-3 and neither worked on recommending artifact nor the artifact posted in the picture above.

**Comment by DevDokus** [comment]
This has nothing to do with what version you use on artifacts. I am using the latest recommended artifacts, even tried to use the latest optional once, and on all of the artifacts I am getting the same error. For now i am going to stay on 1.8.1 and not switching over until this is fixed.

**Comment by thelindat** [comment]
> But I find it funny that the issue ticket is already closed, while the issue still persist.

![image](https://user-images.githubusercontent.com/65407488/144637684-ccbc44e0-6981-43aa-896c-78f30184f9d7.png)
That issue does _not_ persist. You're free to go back to ghmatti or mysql-async if you'd prefer since you want to be an arse.

**Comment by DevDokus** [comment]
uhmmm.. I am not here to be an "arse", I came here as I was getting this error after the last updates. Your saying it is depending on the artifacts, so I tried a couple of them, and I come back to give you the result. If you find that being an arse? okey.
I am simply here to let you know what I experience, and that there is an error on the latest release, if you find that complaining...  Hmmm okey again.  Just here to give some feedback and you go haywire, and say I am an arse?  ^^ Okey

**Comment by thelindat** [comment]
> uhmmm.. I am not here to be an "arse"

"But I find it funny that the issue ticket is already closed, while the issue still persist."
Comes across as fairly arse-like.

> I came here as I was getting this error after the last updates

options error is not the same as the reference error, which is what was reported in the first place.

> But fyi: It has been fixed in Ox v1.8.4. Wasn't easier to just say that ?

A completely different issue was resolved than what was initially reported.
